### ISSUE TITLE
Not working on when change chat view to another, yo can help me to solve on actual version ?

### ISSUE THREAD

**Issue by pwebdev** [chyke007/whatsapp-group-bot#2]
I will thank you if possible.

**Comment by chyke007** [comment]
Hi @pwebdev, perhaps there has been some changes to WhatsApp web, would look into this issue.

Thanks for pointing it out.

**Comment by chyke007** [comment]
Hi @pwebdev ,

I just carried out some test, and I can confirm everything works perfectly.

Can you be explicit as to what issues you are facing?
